// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	keychain "github.com/thxhix/passKeeper/internal/domain/keychain"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto(in *jlexer.Lexer, out *TextResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto(out *jwriter.Writer, in TextResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TextResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TextResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TextResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TextResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto1(in *jlexer.Lexer, out *GetKeysResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "keys":
			if in.IsNull() {
				in.Skip()
				out.Keys = nil
			} else {
				in.Delim('[')
				if out.Keys == nil {
					if !in.IsDelim(']') {
						out.Keys = make([]*GetKeysRecord, 0, 8)
					} else {
						out.Keys = []*GetKeysRecord{}
					}
				} else {
					out.Keys = (out.Keys)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *GetKeysRecord
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(GetKeysRecord)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v1).UnmarshalEasyJSON(in)
						}
					}
					out.Keys = append(out.Keys, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto1(out *jwriter.Writer, in GetKeysResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keys\":"
		out.RawString(prefix[1:])
		if in.Keys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Keys {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetKeysResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetKeysResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetKeysResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetKeysResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto1(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto2(in *jlexer.Lexer, out *GetKeysRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.KeyUUID).UnmarshalText(data))
				}
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KeyType = keychain.KeyType(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto2(out *jwriter.Writer, in GetKeysRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.KeyUUID).MarshalText())
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.KeyType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetKeysRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetKeysRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetKeysRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetKeysRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto2(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto3(in *jlexer.Lexer, out *GetKeyResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.KeyUUID).UnmarshalText(data))
				}
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KeyType = keychain.KeyType(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto3(out *jwriter.Writer, in GetKeyResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.KeyUUID).MarshalText())
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.KeyType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Raw((in.Data).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetKeyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetKeyResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetKeyResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetKeyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto3(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto4(in *jlexer.Lexer, out *FileResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto4(out *jwriter.Writer, in FileResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Note != "" {
		const prefix string = ",\"note\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto4(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto5(in *jlexer.Lexer, out *CredentialsResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "login":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Login = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "site":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Site = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto5(out *jwriter.Writer, in CredentialsResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	if in.Site != "" {
		const prefix string = ",\"site\":"
		out.RawString(prefix)
		out.String(string(in.Site))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CredentialsResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CredentialsResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CredentialsResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CredentialsResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto5(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto6(in *jlexer.Lexer, out *CardResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Number = string(in.String())
			}
		case "exp_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpDate = string(in.String())
			}
		case "cvv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CVV = string(in.String())
			}
		case "holder":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Holder = string(in.String())
			}
		case "bank":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bank = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto6(out *jwriter.Writer, in CardResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix[1:])
		out.String(string(in.Number))
	}
	{
		const prefix string = ",\"exp_date\":"
		out.RawString(prefix)
		out.String(string(in.ExpDate))
	}
	{
		const prefix string = ",\"cvv\":"
		out.RawString(prefix)
		out.String(string(in.CVV))
	}
	{
		const prefix string = ",\"holder\":"
		out.RawString(prefix)
		out.String(string(in.Holder))
	}
	if in.Bank != "" {
		const prefix string = ",\"bank\":"
		out.RawString(prefix)
		out.String(string(in.Bank))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CardResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CardResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CardResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CardResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto6(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto7(in *jlexer.Lexer, out *AddTextDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto7(out *jwriter.Writer, in AddTextDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddTextDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddTextDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddTextDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddTextDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto7(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto8(in *jlexer.Lexer, out *AddSuccessResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key_uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto8(out *jwriter.Writer, in AddSuccessResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key_uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddSuccessResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddSuccessResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddSuccessResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddSuccessResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto8(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto9(in *jlexer.Lexer, out *AddFileDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto9(out *jwriter.Writer, in AddFileDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddFileDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddFileDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddFileDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddFileDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto9(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto10(in *jlexer.Lexer, out *AddCredentialsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "login":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Login = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "site":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Site = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto10(out *jwriter.Writer, in AddCredentialsDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix)
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	if in.Site != "" {
		const prefix string = ",\"site\":"
		out.RawString(prefix)
		out.String(string(in.Site))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddCredentialsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddCredentialsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddCredentialsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddCredentialsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto10(l, v)
}
func easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto11(in *jlexer.Lexer, out *AddCardDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "number":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Number = string(in.String())
			}
		case "exp_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpDate = string(in.String())
			}
		case "cvv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CVV = string(in.String())
			}
		case "holder":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Holder = string(in.String())
			}
		case "bank":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bank = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto11(out *jwriter.Writer, in AddCardDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix)
		out.String(string(in.Number))
	}
	{
		const prefix string = ",\"exp_date\":"
		out.RawString(prefix)
		out.String(string(in.ExpDate))
	}
	{
		const prefix string = ",\"cvv\":"
		out.RawString(prefix)
		out.String(string(in.CVV))
	}
	{
		const prefix string = ",\"holder\":"
		out.RawString(prefix)
		out.String(string(in.Holder))
	}
	if in.Bank != "" {
		const prefix string = ",\"bank\":"
		out.RawString(prefix)
		out.String(string(in.Bank))
	}
	if in.Note != "" {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddCardDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddCardDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE615605cEncodeGithubComThxhixPassKeeperInternalTransportHttpDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddCardDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddCardDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE615605cDecodeGithubComThxhixPassKeeperInternalTransportHttpDto11(l, v)
}
